"""Graph and report writers.

* :class:`GraphWriter` exports the SQLite graph to ``graph.json`` and copies
  the static ``graph.html`` viewer alongside it.
* :class:`ReportWriter` renders the human-facing Markdown findings document
  and, on subsequent runs, a delta report covering everything new since the
  previous run.
"""

from __future__ import annotations

import json
import shutil
from collections import defaultdict
from datetime import datetime, timezone
from importlib import resources
from pathlib import Path
from typing import Any

from dirk.config import Config
from dirk.storage import GraphStore


class GraphWriter:
    """Persist the graph to JSON and render a self-contained HTML viewer."""

    def __init__(self, config: Config, store: GraphStore):
        self.config = config
        self.store = store

    def write(self) -> dict[str, Path]:
        graph_dir = self.config.graph_dir
        graph_dir.mkdir(parents=True, exist_ok=True)

        json_path = graph_dir / "graph.json"
        html_path = graph_dir / "graph.html"

        export = self.store.to_cytoscape()
        json_path.write_text(json.dumps(export, indent=2, sort_keys=True), encoding="utf-8")
        embedded_graph = json.dumps(export, sort_keys=True).replace("</", "<\\/")

        frontend_dist = self.config.root / "frontend" / "dist"
        if frontend_dist.exists():
            assets_src = frontend_dist / "assets"
            assets_dst = graph_dir / "assets"
            if assets_dst.exists():
                shutil.rmtree(assets_dst)
            if assets_src.exists():
                shutil.copytree(assets_src, assets_dst)

            html_template = (frontend_dist / "index.html").read_text(encoding="utf-8")
            embedded_script = (
                f'<script id="dirk-graph-data" type="application/json">{embedded_graph}</script>'
            )
            html_path.write_text(
                html_template.replace("</body>", f"  {embedded_script}\n  </body>", 1),
                encoding="utf-8",
            )
            return {"json": json_path, "html": html_path, "db": self.store.path}

        viewer_src = resources.files("dirk.templates").joinpath("graph.html")
        with resources.as_file(viewer_src) as src_path:
            template = src_path.read_text(encoding="utf-8")

        # Escape closing tags so arbitrary text in graph data can't end the script tag.
        html_path.write_text(
            template.replace("__DIRK_GRAPH_DATA__", embedded_graph, 1),
            encoding="utf-8",
        )

        return {"json": json_path, "html": html_path, "db": self.store.path}


class ReportWriter:
    """Render Markdown findings + delta documents."""

    def __init__(self, config: Config, store: GraphStore):
        self.config = config
        self.store = store

    # -- main report -----------------------------------------------------

    def write_findings(self) -> Path:
        findings_dir = self.config.findings_dir
        findings_dir.mkdir(parents=True, exist_ok=True)

        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        out_path = findings_dir / f"{today}-findings.md"
        latest_path = findings_dir / "latest.md"

        body = self._render_findings(today)
        out_path.write_text(body, encoding="utf-8")
        latest_path.write_text(body, encoding="utf-8")
        return out_path

    def _render_findings(self, today: str) -> str:
        nodes_by_kind: dict[str, list] = defaultdict(list)
        for n in self.store.iter_nodes():
            nodes_by_kind[n.kind].append(n)

        edges_by_kind: dict[str, list] = defaultdict(list)
        for e in self.store.iter_edges():
            edges_by_kind[e["kind"]].append(e)

        threshold = self.config.connection_threshold

        lines: list[str] = []
        lines.append(f"# Holistic Discovery — Findings ({today})")
        lines.append("")
        lines.append("> *\"Everything is connected. The interconnectedness of all things.\"*")
        lines.append("")
        lines.append("Generated by **Dirk**, the holistic research agent.")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        total_nodes = sum(len(v) for v in nodes_by_kind.values())
        total_edges = sum(len(v) for v in edges_by_kind.values())
        lines.append(f"- **Nodes:** {total_nodes}")
        lines.append(f"- **Edges:** {total_edges}")
        lines.append(f"- **Connection threshold:** {threshold:.2f} (weaker edges live in the graph but are omitted below)")
        lines.append(f"- **Serendipity:** {self.config.serendipity:.2f}")
        lines.append("")

        # Repos
        repos = nodes_by_kind.get("Repo", [])
        lines.append(f"## Repositories in scope ({len(repos)})")
        lines.append("")
        if not repos:
            lines.append("_No repositories were inventoried — check `repos.yml`._")
        else:
            for r in sorted(repos, key=lambda n: n.id):
                desc = r.properties.get("description") or ""
                lang = r.properties.get("language") or ""
                topics = ", ".join(r.properties.get("topics") or [])
                bits: list[str] = []
                if lang:
                    bits.append(f"`{lang}`")
                if topics:
                    bits.append(f"topics: {topics}")
                meta = " — " + " · ".join(bits) if bits else ""
                lines.append(f"- **{r.name}**{meta}")
                if desc:
                    lines.append(f"    > {desc}")
        lines.append("")

        # Direct connections
        direct_kinds = ("DEPENDS_ON", "EXPOSES", "MENTIONS", "AUTHORED_BY")
        direct_edges = [
            e for k in direct_kinds for e in edges_by_kind.get(k, [])
            if e["confidence"] >= threshold
        ]
        lines.append(f"## Direct connections ({len(direct_edges)})")
        lines.append("")
        if not direct_edges:
            lines.append("_No direct connections at or above the threshold yet._")
        else:
            for e in sorted(direct_edges, key=lambda x: (-x["confidence"], x["src"], x["dst"])):
                lines.append(self._fmt_edge(e))
        lines.append("")

        # Latent connections
        latent_kinds = ("SIMILAR_TO", "EVOLVED_FROM")
        latent_edges = [
            e for k in latent_kinds for e in edges_by_kind.get(k, [])
            if e["confidence"] >= threshold
        ]
        lines.append(f"## Latent connections ({len(latent_edges)})")
        lines.append("")
        if not latent_edges:
            lines.append("_No latent connections yet — the semantic linker (Phase 3) will fill this in._")
        else:
            for e in sorted(latent_edges, key=lambda x: -x["confidence"]):
                lines.append(self._fmt_edge(e))
        lines.append("")

        # Suggested compositions
        compose = [
            e for e in edges_by_kind.get("COULD_COMPOSE_WITH", [])
            if e["confidence"] >= threshold
        ]
        lines.append(f"## Suggested compositions ({len(compose)})")
        lines.append("")
        if not compose:
            lines.append("_No composition suggestions yet — the curator (Phase 4) needs more upstream signal._")
        else:
            for e in sorted(compose, key=lambda x: -x["confidence"]):
                lines.append(self._fmt_edge(e))
        lines.append("")

        # Trail
        lines.append("---")
        lines.append("")
        lines.append("_This document is generated. Edit Dirk's skills, not this file._")
        lines.append(f"_Graph artifacts: `{self.config.graph_dir}/graph.db`, `graph.json`, `graph.html`._")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _fmt_edge(edge: dict[str, Any]) -> str:
        evidence = edge.get("evidence") or []
        ev_text = ""
        if evidence:
            joined = "; ".join(
                (ev.get("note") or ev.get("ref") or "") for ev in evidence if isinstance(ev, dict)
            )
            if joined:
                ev_text = f" — _{joined}_"
        return (
            f"- `{edge['kind']}` **{edge['src']}** → **{edge['dst']}** "
            f"(confidence {edge['confidence']:.2f}, via `{edge['discovered_by']}`)"
            f"{ev_text}"
        )

    # -- delta report ----------------------------------------------------

    def write_delta(self, previous_snapshot: dict[str, Any] | None) -> Path | None:
        """Write a delta report comparing the current graph to *previous_snapshot*.

        Returns the path written, or ``None`` if there is no prior snapshot.
        """
        if previous_snapshot is None:
            return None
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        out_path = self.config.findings_dir / f"delta-{today}.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)

        prior_node_ids = {el["data"]["id"] for el in previous_snapshot.get("elements", [])
                          if "source" not in el["data"]}
        prior_edge_ids = {el["data"]["id"] for el in previous_snapshot.get("elements", [])
                          if "source" in el["data"]}

        current = self.store.to_cytoscape()
        cur_nodes = [el for el in current["elements"] if "source" not in el["data"]]
        cur_edges = [el for el in current["elements"] if "source" in el["data"]]

        new_nodes = [el for el in cur_nodes if el["data"]["id"] not in prior_node_ids]
        new_edges = [el for el in cur_edges if el["data"]["id"] not in prior_edge_ids]

        lines = [f"# Holistic Discovery — Delta ({today})", ""]
        lines.append(f"Compared against the previous snapshot of `graph.json`.")
        lines.append("")
        lines.append(f"## New nodes ({len(new_nodes)})")
        lines.append("")
        if not new_nodes:
            lines.append("_No new nodes._")
        for el in new_nodes:
            d = el["data"]
            lines.append(f"- `{d.get('kind','?')}` **{d.get('label', d['id'])}**")
        lines.append("")
        lines.append(f"## New edges ({len(new_edges)})")
        lines.append("")
        if not new_edges:
            lines.append("_No new edges._")
        for el in new_edges:
            d = el["data"]
            lines.append(f"- `{d.get('kind','?')}` {d.get('source')} → {d.get('target')} "
                         f"(confidence {d.get('confidence', 0):.2f}, via `{d.get('discovered_by','?')}`)")
        lines.append("")

        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return out_path
